name: Auto Reply to New Issues

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Add Comment to New Issue
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "👋 Thanks for opening this issue! We’ll review it shortly. If you’d like to contribute, feel free to check the [Contributing Guide](https://github.com/sakoliactepl/Resource-Tracker-Application-Angular-Frontend/blob/main/CONTRIBUTING.md). 🚀"
          })
